# 提示词库同步配置 - 基于Excel完整数据
source:
  excel_file: "prompt (2).xlsx" 
  total_rows: 18
  total_cols: 3
  processed_date: "2025-02-02"

google_sheets:
  sheet_id: "1ngoQOhJqdguwNAilCl1joNwTje7FWWN9WiI2bo5VhpU"
  credentials_path: "./credentials.json"
  
output:
  prompts_dir: "./prompts"
  use_timestamp: true
  
naming:
  max_title_length: 30
  row_col_format: "({row},{col})"
  separator: "_"
  
sync:
  skip_rows: []  # 不跳过任何行，完整处理
  skip_keywords: []  # 完整保留所有内容
  
# Excel原始数据映射
excel_mapping:
  prompts:
    - row: 0
      title: "提示词1a"
      versions: [1, 2, 3]
      content: ["提示词1a", "提示词1b", "提示词1c"]
    - row: 1  
      title: "提示词2a"
      versions: [1, 2]
      content: ["提示词2a", "提示词2b"]
    - row: 3
      title: "提示词ya"
      versions: [1]
      content: ["提示词ya"]
  
  tools:
    openai_optimizer:
      row: 5
      url: "https://platform.openai.com/chat/edit?models=gpt-5&optimize=true"
      description: "openai提示词优化网站"
  
  social_media:
    twitter:
      row: 7
      url: "https://x.com/123olp" 
      description: "点击关注我的推特，获取最新动态，首页接广告位"
  
  support:
    title_row: 9
    title: "礼貌要饭地址"
    crypto_wallets:
      tron:
        row: 10
        address: "TQtBXCSTwLFHjBqTS4rNUp7ufiGx51BRey"
      solana:
        row: 11
        address: "HjYhozVf9AQmfv7yv79xSNs6uaEU5oUk2USasYQfUYau"
      ethereum:
        row: 12
        address: "0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC"
      bsc:
        row: 13
        address: "0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC"
      bitcoin:
        row: 14
        address: "bc1plslluj3zq3snpnnczplu7ywf37h89dyudqua04pz4txwh8z5z5vsre7nlm"
      sui:
        row: 15
        address: "0xb720c98a48c77f2d49d375932b2867e793029e6337f1562522640e4f84203d2e"
  
  misc:
    warning:
      row: 17
      content: "广告位（注意识别风险）"

# 数据验证规则
validation:
  prompt_rows: [0, 1, 3]
  tool_rows: [5]
  social_rows: [7]
  crypto_rows: [10, 11, 12, 13, 14, 15]
  warning_rows: [17]